<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Wowlib" Version="0.0.10" />
    <ProjectReference Include="../../DBCD/DBCD.IO/DBCD.IO.csproj" />
    <ProjectReference Include="../../WoWRenderLib/WoWRenderLib.csproj" />
  </ItemGroup>
</Project>
